name: Deploy to Deta
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      - uses: BogDAAAMN/deta-deploy-action@v1.0.0
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'toornament-py'
          deta-project: 'default'
